package:
  name: enaml-native-cli
  version: 3.0.0

channels:
 - conda-forge

# On linux you must apt install build-essential autopoint texinfo
requirements:
  build:
    - python
  run:
    - pip
    - requests
    - atom
    - tornado
    - libtool
    - autoconf
    - automake
    - cookiecutter
    - sh
    - ruamel.yaml
    - watchdog

build:
  number: 0
  noarch: python
  include_recipe: False
  script:
    - cd $RECIPE_DIR
    - python setup.py install --single-version-externally-managed --record=record.txt --no-compile
  entry_points:
    - enaml-native = enamlnativecli.main:main
about:
  home: http://github.com/codelv/enaml-native-cli
  summary: "CLI for building android and iOS apps using enaml-native"
  license: GPLv3
