target '{{cookiecutter.project_name}}' do
  use_frameworks!
  pod "MPMessagePack", :git => 'https://github.com/gabriel/MPMessagePack.git'

  pod "BlocksKit"
  pod 'YogaKit', '~> 1.6'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end