name: CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.9', '3.10']
        ndk-version: ['23.1.7779620']
    steps:
      - uses: actions/checkout@v2
      - name: Setup python ${{ matrix.python-version}}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: Install test dependencies
        run: pip install -U atom enaml tornado msgpack codecov pytest pytest-cov pytest-asyncio
      - name: Install cli
        run: |
            pip install --user git+https://github.com/codelv/enaml-native-cli.git
            enaml-native -h
      - name: Install enaml-native
        run: pip install -e ./
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Setup Android NDK
        run: |
            export ANDROID_HOME="$HOME/Android/Sdk"
            export ANDROID_SDK_ROOT="$HOME/Android/Sdk"
            export PATH="$PATH:$ANDROID_HOME/cmdline-tools/latest/bin"
            mkdir -p $ANDROID_HOME
            wget -q https://dl.google.com/android/repository/commandlinetools-linux-8092744_latest.zip
            unzip commandlinetools-linux-8092744_latest.zip -d $ANDROID_HOME/cmdline-tools
            mv $ANDROID_HOME/cmdline-tools/cmdline-tools $ANDROID_HOME/cmdline-tools/latest
            yes | sdkmanager --licenses
            yes | sdkmanager --install tools
            yes | sdkmanager --install platform-tools
            yes | sdkmanager --install ndk-bundle
            yes | sdkmanager --install "ndk;${{ matrix.ndk-version}}"
      - name: Install android system image and emulator
        run: |
          sdkmanager --list
          sdkmanager --install "system-images;android-30;google_apis;x86_64"
          sdkmanager --install "emulator"
      - name: Create avd
        run: |
          echo no | avdmanager create avd --force --name test -k "system-images;android-30;google_apis;x86_64"
          avdmanager list avd
      - name: Start emulator
        run: |
          export PATH="$PATH:$ANDROID_HOME/emulator"
          emulator -avd test -no-audio -no-window -no-accel &
          timeout 300 adb wait-for-device
          adb devices
      - name: Run tests
        run: pytest -v tests --cov enamlnativecli --cov-report xml --asyncio-mode auto
      - name: Coverage
        run: codecov
  check-code:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10']
    steps:
      - uses: actions/checkout@v2
      - name: Setup python ${{ matrix.python-version}}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: pip install -U mypy black isort flake8
      - name: Run checks
        run: |
            isort enamlnativecli --check --diff
            isort tests --check --diff
            black enamlnativecli/main.py --check --diff
            black tests --check --diff
            flake8 --ignore=E501 enamlnativecli --per-file-ignores=enamlnativecli/templates/*:E999
            flake8 --ignore=E501 tests
            mypy enamlnativecli --ignore-missing-imports


